language: php

php:
  - 5.6

services: 
  - mysql


before_install:
  - cp .env.travis .env
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - composer self-update
  - composer install --no-interaction
  

script:
  - vendor/bin/phpunit