language: php

php:
  - 5.6

services: 
  - mysql

test:
  adapter: mysql2
  database: testing
  username: root
  encoding: utf8


before_install:
  - cp .env.travis .env
  - mysql -e "create database IF NOT EXISTS testing;" -uroot

before_script:
  - composer self-update
  - composer install --no-interaction
  

script:
  - vendor/bin/phpunit