<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class RegistrationControllerTest extends TestCase
{
    /**
     * Test User Registration functionality
     *
     * @return void
     */
    
    public function setUp()
    {
        parent::setUp();

        Artisan::call('migrate');

        if(app()->env == "testing"){
            Artisan::call('db:seed', ['--class' => 'ProgramSeeder']);

            $sql = "CREATE TABLE IF NOT EXISTS `programs` (
  `PROGRAM_ID` int(11) DEFAULT NULL,
  `VERSION` int(11) DEFAULT NULL,
  `TERM_CODE_KEY` int(11) DEFAULT NULL,
  `TERM` varchar(9) DEFAULT NULL,
  `PROGRAM` varchar(11) DEFAULT NULL,
  `FIELD_OF_STUDY` varchar(13) DEFAULT NULL,
  `PROGRAM_MAJOR_CODE` varchar(4) DEFAULT NULL,
  `PROGRAM_MAJOR` varchar(30) DEFAULT NULL,
  `PROGRAM_MAJOR_CODE_ATTACH_X` varchar(4) DEFAULT NULL,
  `PROGRAM_MAJOR_ATTACH_X` varchar(27) DEFAULT NULL,
  `PROGRAM_FACULTY_CODE` varchar(2) DEFAULT NULL,
  `PROGRAM_FACULTY` varchar(22) DEFAULT NULL,
  `PROGRAM_TEACHING_FACULTY_CODE` varchar(2) DEFAULT NULL,
  `PROGRAM_TEACHING_FACULTY` varchar(22) DEFAULT NULL,
  `PROGRAM_DEGREE_CODE` varchar(6) DEFAULT NULL,
  `PROGRAM_DEGREE` varchar(26) DEFAULT NULL,
  `PROGRAM_LEVEL_CODE` varchar(2) DEFAULT NULL,
  `PROGRAM_LEVEL` varchar(13) DEFAULT NULL,
  `DEPARTMENT_CODE` int(11) DEFAULT NULL,
  `DEPARTMENT` varchar(30) DEFAULT NULL,
  `CALENDAR_TITLE_ENGLISH` varchar(92) DEFAULT NULL,
  `CALENDAR_TITLE_FRENCH` int(11) DEFAULT NULL,
  `CALENDAR_DESC_ENGLISH` varchar(1596) DEFAULT NULL,
  `CALENDAR_DESC_FRENCH` int(11) DEFAULT NULL,
  `PROGRAM_TOTAL_CREDITS` int(11) DEFAULT NULL,
  `SET_NUMBER` int(11) DEFAULT NULL,
  `SUBSET_OF` int(11) DEFAULT NULL,
  `SET_DEPTH` int(11) DEFAULT NULL,
  `SET_SUBSET_HIERARCHY` varchar(7) DEFAULT NULL,
  `SET_NUMBER_1` int(11) DEFAULT NULL,
  `SET_NUMBER_2` int(11) DEFAULT NULL,
  `SET_NUMBER_3` int(11) DEFAULT NULL,
  `SET_NUMBER_4` int(11) DEFAULT NULL,
  `SET_TYPE_CODE` varchar(1) DEFAULT NULL,
  `SET_TYPE` varchar(13) DEFAULT NULL,
  `SET_TITLE_ENGLISH` varchar(75) DEFAULT NULL,
  `SET_BEGIN_TEXT_ENGLISH` varchar(1860) DEFAULT NULL,
  `SET_END_TEXT_ENGLISH` varchar(331) DEFAULT NULL,
  `SET_TITLE_FRENCH` int(11) DEFAULT NULL,
  `SET_BEGIN_TEXT_FRENCH` int(11) DEFAULT NULL,
  `SET_END_TEXT_FRENCH` int(11) DEFAULT NULL,
  `SET_REVISED_DATE` varchar(19) DEFAULT NULL,
  `SET_CREDITS` int(11) DEFAULT NULL,
  `SUBJECT_CODE` varchar(4) DEFAULT NULL,
  `SUBJECT` varchar(30) DEFAULT NULL,
  `COURSE_NUMBER` varchar(5) DEFAULT NULL,
  `COURSE_TITLE` varchar(59) DEFAULT NULL,
  `ACADEMIC_YEAR` int(11) DEFAULT NULL,
  `COURSE_CREDITS` int(11) DEFAULT NULL,
  `COURSE_SYMBOL` varchar(3) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY1_CODE` varchar(2) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE1_CODE` varchar(6) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE1` varchar(26) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY2_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY2` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE2_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE2` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY3_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY3` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE3_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE3` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY4_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY4` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE4_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE4` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY5_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY5` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE5_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE5` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY6_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY6` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE6_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE6` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY7_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY7` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE7_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE7` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY8_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY8` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE8_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE8` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY9_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY9` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE9_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE9` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY10_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY10` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE10_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE10` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY11_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_FACULTY11` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE11_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEGREE11` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT1_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT1` varchar(30) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT2_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT2` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT3_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT3` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT4_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT4` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT5_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT5` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT6_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT6` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT7_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT7` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT8_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT8` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT9_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT9` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT10_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT10` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT11_CODE` int(11) DEFAULT NULL,
  `PROGRAM_DISPLAY_DEPT11` int(11) DEFAULT NULL,
  `REFRESH_DATE_TIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;";
            DB::raw($sql);
        }
    }

    public function testUserRegistrationValid()
    {
        $this->visit('/auth/registration')
            ->see("First, Let's Get Your McGill E-mail and Password for Your New Account.")
            ->type('thomas.karatzas@mail.mcgill.ca', 'Email')
            ->type('Thomas', 'First_Name')
            ->type('Karatzas', 'Last_Name')
            ->type('8characterPass', 'Password')
            ->type('8characterPass', 'Confirm_Password')
            ->press('Submit')
            ->seePageIs('/flowchart');
    }
}
